# Generated by Django 5.2.16 on 2026-07-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='نام و نام خانوادگی')),
                ('personnel_code', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='کد پرسنلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اپراتور',
                'verbose_name_plural': 'اپراتورها',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام گروه محصول')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه\u200cهای محصول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام خط تولید')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='کد خط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'خط تولید',
                'verbose_name_plural': 'خطوط تولید',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام ماده اولیه')),
                ('unit', models.CharField(default='کیلوگرم', max_length=30, verbose_name='واحد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام شیفت')),
                ('starts_at', models.TimeField(verbose_name='شروع')),
                ('ends_at', models.TimeField(verbose_name='پایان')),
            ],
            options={
                'verbose_name': 'شیفت',
                'verbose_name_plural': 'شیفت\u200cها',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نوع ضایعات')),
                ('category', models.CharField(choices=[('reusable', 'قابل مصرف مجدد'), ('saleable', 'ضایعات فروشی'), ('disposal', 'دورریز')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع ضایعات',
                'verbose_name_plural': 'انواع ضایعات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام محصول')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='کد محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productgroup', verbose_name='گروه محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['group__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='تاریخ')),
                ('crew_count', models.PositiveIntegerField(verbose_name='تعداد نفرات شیفت')),
                ('total_production', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تولید کل')),
                ('useful_production', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تولید مفید')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionline', verbose_name='خط تولید')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.operator', verbose_name='اپراتور مسئول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product', verbose_name='محصول تولیدی')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.shift', verbose_name='شیفت')),
            ],
            options={
                'verbose_name': 'گزارش تولید',
                'verbose_name_plural': 'گزارش\u200cهای تولید',
                'ordering': ['-report_date', 'line__name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار مصرف')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productionreport', verbose_name='گزارش تولید')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'مصرف ماده',
                'verbose_name_plural': 'مصرف مواد',
            },
        ),
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='production.productionreport', verbose_name='گزارش تولید')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.wastetype', verbose_name='نوع ضایعات')),
            ],
            options={
                'verbose_name': 'ضایعات',
                'verbose_name_plural': 'ضایعات',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_product_per_group'),
        ),
        migrations.AddConstraint(
            model_name='materialconsumption',
            constraint=models.UniqueConstraint(fields=('report', 'material'), name='unique_material_per_report'),
        ),
        migrations.AddConstraint(
            model_name='wasteentry',
            constraint=models.UniqueConstraint(fields=('report', 'waste_type'), name='unique_waste_per_report'),
        ),
    ]
