# Generated by Django 5.2.16 on 2026-07-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionline',
            options={'ordering': ['group__name', 'name'], 'verbose_name': 'خط تولید', 'verbose_name_plural': 'خطوط تولید'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['group__name', 'name'], 'verbose_name': 'ماده اولیه', 'verbose_name_plural': 'مواد اولیه'},
        ),
        migrations.AlterModelOptions(
            name='wastetype',
            options={'ordering': ['group__name', 'category', 'name'], 'verbose_name': 'نوع ضایعات', 'verbose_name_plural': 'انواع ضایعات'},
        ),
        migrations.AddField(
            model_name='productionline',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='production.productgroup', verbose_name='گروه محصول'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='production.productgroup', verbose_name='گروه محصول'),
        ),
        migrations.AddField(
            model_name='wastetype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_types', to='production.productgroup', verbose_name='گروه محصول'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نوع ضایعات'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_raw_material_per_group'),
        ),
        migrations.AddConstraint(
            model_name='wastetype',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_waste_type_per_group'),
        ),
    ]
