# Generated by Django 5.2.16 on 2026-07-30 12:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumption',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مقدار مصرف'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='crew_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد نفرات شیفت'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='total_production',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='تولید کل'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='useful_production',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='تولید مفید'),
        ),
        migrations.AlterField(
            model_name='wasteentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مقدار'),
        ),
    ]
