# Generated by Django 5.2.16 on 2026-07-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_materialconsumption_quantity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productionreport',
            constraint=models.UniqueConstraint(fields=('report_date', 'line', 'shift'), name='unique_report_per_date_line_shift'),
        ),
    ]
