# Generated by Django 5.2.16 on 2026-08-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionreport_unique_report_per_date_line_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['group__name', 'full_name'], 'verbose_name': 'اپراتور', 'verbose_name_plural': 'اپراتورها'},
        ),
        migrations.AddField(
            model_name='operator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='production.productgroup', verbose_name='گروه محصول'),
        ),
    ]
