# Generated by Django 5.2.16 on 2026-08-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_operator_options_operator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='production.productgroup', verbose_name='گروه محصول'),
        ),
    ]
